deploy:
    needs: main
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: ACTIONS_ALLOW_UNSECURE_COMMANDS
        run: echo 'ACTIONS_ALLOW_UNSECURE_COMMANDS=true' >> $GITHUB_ENV
      - uses: chrislennon/action-aws-cli@v1.1
      - run: aws s3 sync dist/apps s3://${{ secrets.AWS_S3_BUCKET_NAME }}/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
